---
# https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/set-time.html
- name: Install Chrony
  apt: 
    name: chrony
    update_cache: yes
  become: yes

- name: Copy Chrony Configuration
  template:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: Chrony Restart
  become: yes
